// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpP-w711EIaU1dilxMiOrlD6WfeNmUn-0',
    appId: '1:979263977770:web:eab975452896326fac8653',
    messagingSenderId: '979263977770',
    projectId: 'notes-a07b7',
    authDomain: 'notes-a07b7.firebaseapp.com',
    storageBucket: 'notes-a07b7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIgUxhnLvcdyzpGVz2VkpLUg6y8ImCVKE',
    appId: '1:979263977770:android:02abfdfd0d1f4169ac8653',
    messagingSenderId: '979263977770',
    projectId: 'notes-a07b7',
    storageBucket: 'notes-a07b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0kubZmpg8WXw6u_NmPX7FPbWPqE6ayIQ',
    appId: '1:979263977770:ios:c02d435b21dee1abac8653',
    messagingSenderId: '979263977770',
    projectId: 'notes-a07b7',
    storageBucket: 'notes-a07b7.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0kubZmpg8WXw6u_NmPX7FPbWPqE6ayIQ',
    appId: '1:979263977770:ios:c02d435b21dee1abac8653',
    messagingSenderId: '979263977770',
    projectId: 'notes-a07b7',
    storageBucket: 'notes-a07b7.appspot.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpP-w711EIaU1dilxMiOrlD6WfeNmUn-0',
    appId: '1:979263977770:web:6a59b7059b5b46edac8653',
    messagingSenderId: '979263977770',
    projectId: 'notes-a07b7',
    authDomain: 'notes-a07b7.firebaseapp.com',
    storageBucket: 'notes-a07b7.appspot.com',
  );
}
